package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	schema := filepath.Join(root, "web", "report", "schema", "report-dataset-v1.schema.json")
	b, err := os.ReadFile(schema)
	if err != nil {
		panic(err)
	}
	var value any
	if json.Unmarshal(b, &value) != nil {
		panic("invalid report schema")
	}
	sum := sha256.Sum256(b)
	out := filepath.Join(root, "internal", "report", "generated", "manifest.go")
	content := fmt.Sprintf("// Code generated by reportgen; DO NOT EDIT.\npackage generated\n\nconst SchemaSHA256 = %q\n", hex.EncodeToString(sum[:]))
	if err := os.MkdirAll(filepath.Dir(out), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(out, []byte(content), 0644); err != nil {
		panic(err)
	}
}
